Document: config-backup
Title: Debian config-backup Manual
Author: <insert document author here>
Abstract: This manual describes what config-backup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/config-backup/config-backup.sgml.gz

Format: postscript
Files: /usr/share/doc/config-backup/config-backup.ps.gz

Format: text
Files: /usr/share/doc/config-backup/config-backup.text.gz

Format: HTML
Index: /usr/share/doc/config-backup/html/index.html
Files: /usr/share/doc/config-backup/html/*.html
